version: '3' 
services:
  shiny_proxy:
    restart: always
    container_name: oasisui_proxy
    image: coreoasis/oasisui_proxy:latest
    ports:
     - 8080:8080
    environment:
     - UI_DOCKER_IMAGE=coreoasis/oasisui_app:latest
     #- API_IP=<REMOTE_IP>
     - API_PORT=8000
     - API_VERSION=v1
     - API_SHARE_FILEPATH=./downloads
     - OASIS_ENVIRONMENT=oasis_localhost

    links:
     - server
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - shiny-net
     - default  

networks:
  shiny-net:
    external: true
