FROM openanalytics/r-base

MAINTAINER Daan Seynaeve "daan.seynaeve@openanalytics.eu"
MAINTAINER Paul Dragoonis "paul@dragoonis.com"

WORKDIR /workspace

RUN apt-get update -y && apt-get --no-install-recommends install -y \
    sudo \
    gdebi-core \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev \
    tk-dev \
    libssl1.0.0 \
    mesa-common-dev \
    subversion \
    libxml2-dev \
    texlive-base \
    texlive-bibtex-extra \
    texlive-extra-utils \
    texlive-generic-recommended \
    texlive-fonts-recommended \
    texlive-font-utils \
    texlive-latex-base \
    texlive-latex-recommended \
    texlive-latex-extra \
    texlive-math-extra \
    texlive-pictures \
    texlive-pstricks \
    texlive-science \
    perl-tk \
    purifyeps \
    chktex \
    latexmk \
    dvipng \
    dvidvi \
    fragmaster \
    lacheck \
    latexdiff \
    libfile-which-perl \
    dot2tex \
    tipa \
    latex-xcolor \
    latex-beamer \
    prosper \
    pgf \
    texinfo \
    fonts-inconsolata \
    xzdec \
    pandoc \
    pandoc-citeproc \
    default-jdk \
    unixodbc-dev && \
    rm -rf /var/lib/apt/lists/*


COPY src/shell-scripts/entrypoint_tar-builder.sh /tmp/entrypoint.sh
COPY build/inconsolata.tar.xz /tmp/inconsolata.tar.xz

# install inconsolata font for tex
RUN tlmgr init-usertree; exit 0
RUN tlmgr install --file /tmp/inconsolata.tar.xz

# common R dependencies
RUN R CMD javareconf
RUN R -e "options(warn=2); install.packages('rJava', repos='https://cloud.r-project.org')"
RUN R -e "options(warn=2) ; install.packages(c('roxygen2','remotes'))"
RUN R -e "options(warn=2) ; install.packages(c('ggplot2','plotly','leaflet','data.table','dplyr','reshape2','plyr','knitr','rmarkdown','caret','devtools'), repos='https://cloud.r-project.org')"
RUN R -e "options(warn=2) ; update.packages(repos='https://cloud.r-project.org',ask=FALSE)"

RUN R -q -e "install.packages('shiny', repos = 'https://cloud.r-project.org/')" && \
    R -q -e "install.packages('htmltools', repos = 'https://cloud.r-project.org/')" && \
    R -q -e "install.packages('httr', repos = 'https://cloud.r-project.org/')" && \
    R -q -e "install.packages('odbc', repos = 'https://cloud.r-project.org/')" && \
    R -q -e "install.packages('DBI', repos = 'https://cloud.r-project.org/')" && \
    R -q -e "install.packages('xml2', repos = 'https://cloud.r-project.org/')" && \
    R -q -e "install.packages('shinyBS', repos = 'https://cloud.r-project.org/')" && \
    R -q -e "install.packages('shinyjs', repos = 'https://cloud.r-project.org/')" && \
    R -q -e "install.packages('rjson', repos = 'https://cloud.r-project.org/')" && \
    R -q -e "install.packages('DT', repos = 'https://cloud.r-project.org/')" && \
    R -q -e "install.packages('logging', repos = 'https://cloud.r-project.org/')" && \
    R -q -e "devtools::install_github('rstudio/shinytest')"

VOLUME /workspace

RUN apt-get update -y && apt-get install nano && rm -rf /var/lib/apt/lists/*

# Create and switch to jenkins user
ARG USER_ID
RUN adduser --shell /bin/bash --uid $USER_ID jenkins && \
    chown -R jenkins:jenkins . && \
    chown -R jenkins:jenkins /tmp/entrypoint.sh && \
    chmod +x /tmp/entrypoint.sh
USER jenkins

CMD /tmp/entrypoint.sh
