version: '2' 
services:

  shiny_proxy:
    restart: always
    container_name: shiny_proxy
    image: coreoasis/shiny_proxy:__flamingo_release_tag__
    ports:
     - 8080:8080
    environment:
     - FLAMINGO_ENVIRONMENT=__sql_env_name__
     - FLAMINGO_API_PORT=8000
     - FLAMINGO_DB_IP=__sql_ip__
     - FLAMINGO_DB_PORT=__sql_port__
     - FLAMINGO_DB_NAME=Flamingo___sql_env_name__
     - FLAMINGO_DB_USERNAME=__sql_env_name__
     - FLAMINGO_DB_PASSWORD=__sql_env_pass__
     - FLAMINGO_PORT_RANGE_START=20000
     - FLAMINGO_DOCKER_IMAGE=coreoasis\/flamingo_shiny:__flamingo_release_tag__
     - FLAMINGO_SHARE_FILEPATH_ON_HOST=/home/centos/flamingo_share/Files

  flamingo_server:
    restart: always
    container_name: flamingo_server
    image: coreoasis/flamingo_server:__flamingo_release_tag__
    volumes:
      - ./flamingo_share/Files:/var/www/oasis/Files
    ports:
      - 8000:80
    extra_hosts:
      - oasis_api_server:__ip_address__
    environment:
      - IS_WINDOWS_HOST=True
      - FLAMINGO_ENVIRONMENT=__sql_env_name__
      - FLAMINGO_DB_IP=__sql_ip__
      - FLAMINGO_DB_PORT=__sql_port__
      - FLAMINGO_DB_NAME=Flamingo___sql_env_name__
      - FLAMINGO_DB_USERNAME=__sql_env_name__
      - FLAMINGO_DB_PASSWORD=__sql_env_pass__
      - OASIS_LOG_LEVEL=DEBUG
