proxy:
  port: 8080
  authentication: none
  docker:
    internal-networking: true
  specs:
  - id: Oasisui
    title: Oasisui Proxy
    display-name: Oasisui
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    container-cmd: ["R", "-e", "oasisui::runOasisui()"]
    container-image: %UI_DOCKER_IMAGE%
    container-env-file: settings.env
    container-network-connections: shiny-net

logging:
  file:
    shinyproxy.log
