version: "3.8"
volumes:
  server-db-OasisData:
  celery-db-OasisData:
  filestore-OasisData:
services:
  server:
    restart: always
    image: ${SERVER_IMG:-coreoasis/api_server}:${VERS_API:-latest}
    ports:
      - 8000:8000
    links:
      - server-db
      - celery-db
      - rabbit
    environment:
      - OASIS_ADMIN_USER=admin
      - OASIS_ADMIN_PASS=password
      - OASIS_DEBUG=1
      - OASIS_RABBIT_HOST=rabbit
      - OASIS_RABBIT_PORT=5672
      - OASIS_RABBIT_USER=rabbit
      - OASIS_RABBIT_PASS=rabbit
      - OASIS_SERVER_DB_HOST=server-db
      - OASIS_SERVER_DB_PASS=oasis
      - OASIS_SERVER_DB_USER=oasis
      - OASIS_SERVER_DB_NAME=oasis
      - OASIS_SERVER_DB_PORT=5432
      - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
      - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
      - OASIS_CELERY_DB_HOST=celery-db
      - OASIS_CELERY_DB_PASS=password
      - OASIS_CELERY_DB_USER=celery
      - OASIS_CELERY_DB_NAME=celery
      - OASIS_CELERY_DB_PORT=5432
      - STARTUP_RUN_MIGRATIONS=true
    volumes:
      - filestore-OasisData:/shared-fs:rw
  worker-monitor:
    restart: always
    image: ${SERVER_IMG:-coreoasis/api_server}:${VERS_API:-latest}
    command:
      [
        wait-for-server,
        "server:8000",
        celery,
        -A,
        src.server.oasisapi,
        worker,
        --loglevel=INFO,
      ]
    links:
      - server-db
      - celery-db
      - rabbit
    environment:
      - OASIS_DEBUG=1
      - OASIS_RABBIT_HOST=rabbit
      - OASIS_RABBIT_PORT=5672
      - OASIS_RABBIT_USER=rabbit
      - OASIS_RABBIT_PASS=rabbit
      - OASIS_SERVER_DB_HOST=server-db
      - OASIS_SERVER_DB_PASS=oasis
      - OASIS_SERVER_DB_USER=oasis
      - OASIS_SERVER_DB_NAME=oasis
      - OASIS_SERVER_DB_PORT=5432
      - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
      - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
      - OASIS_CELERY_DB_HOST=celery-db
      - OASIS_CELERY_DB_PASS=password
      - OASIS_CELERY_DB_USER=celery
      - OASIS_CELERY_DB_NAME=celery
      - OASIS_CELERY_DB_PORT=5432
    volumes:
      - filestore-OasisData:/shared-fs:rw
  worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    links:
      - celery-db
      - rabbit:myrabbit
    environment:
      - OASIS_MODEL_SUPPLIER_ID=OasisLMF
      - OASIS_MODEL_ID=PiWind
      - OASIS_MODEL_VERSION_ID=1
      - OASIS_RABBIT_HOST=rabbit
      - OASIS_RABBIT_PORT=5672
      - OASIS_RABBIT_USER=rabbit
      - OASIS_RABBIT_PASS=rabbit
      - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
      - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
      - OASIS_CELERY_DB_HOST=celery-db
      - OASIS_CELERY_DB_PASS=password
      - OASIS_CELERY_DB_USER=celery
      - OASIS_CELERY_DB_NAME=celery
      - OASIS_CELERY_DB_PORT=5432
      - OASIS_MODEL_DATA_DIRECTORY=/home/worker/model
    volumes:
      - ./OasisPiWind/:/home/worker/model
      - filestore-OasisData:/shared-fs:rw
  server-db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=oasis
      - POSTGRES_USER=oasis
      - POSTGRES_PASSWORD=oasis
    volumes:
      - server-db-OasisData:/var/lib/postgresql/data:rw
  celery-db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=celery
      - POSTGRES_USER=celery
      - POSTGRES_PASSWORD=password
    volumes:
      - celery-db-OasisData:/var/lib/postgresql/data:rw
  rabbit:
    restart: always
    image: rabbitmq:3.8.14-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - 5672:5672
      - 15672:15672
  rstudio:
    image: oasisui_dev:latest
    restart: always
    environment:
      - DISABLE_AUTH=true
      - USERID=${UID:-1000}
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - ${SHARED_DIR}:/home/rstudio/oasisui
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    ports:
      - 8787:8787
    networks:
      - default
