sed -i -e s/%IS_WINDOWS_HOST%/$IS_WINDOWS_HOST/g $1
sed -i -e s/%FLAMINGO_ENVIRONMENT%/$FLAMINGO_ENVIRONMENT/g $1
sed -i -e s/%OASIS_LOG_LEVEL%/$OASIS_LOG_LEVEL/g $1
sed -i -e s/%FLAMINGO_DB_IP%/$FLAMINGO_DB_IP/g $1
sed -i -e s/%FLAMINGO_DB_PORT%/$FLAMINGO_DB_PORT/g $1
sed -i -e s/%FLAMINGO_DB_NAME%/$FLAMINGO_DB_NAME/g $1
sed -i -e s/%FLAMINGO_DB_USERNAME%/$FLAMINGO_DB_USERNAME/g $1
sed -i -e s/%FLAMINGO_DB_PASSWORD%/$FLAMINGO_DB_PASSWORD/g $1
