---
title: "Customizable model"
author: "Nicoletta Farabullini"
date: "3/16/2021"
output: pdf_document
---

New implementations to the OASIS UI workflow have been made to allow users to edit model features upon analysis creation. Previous versions only allowed for model settings to be decided upon model creation, without any possibilities for further changes.
The new edits make it possible to customize model values and select files associated with a model. The new model settings will be saved in the model_settings portion of the analysis settings and will not modify the standard model settings used to initially create the model.

In order for a model to be customisable, the original model settings have to include the option: "model_configurable": [true]. If this option is set to [false] or does not exist, the model settings cannot be modified and the workflow proceeds as in previous versions of the UI. 

Otherwise starting from the "Choose Analysis" step, additional tasks need to completed: 

1. Click on "Create Analysis"
3. Select the customisable model from the models table.
4. The button "Customize model" will be enabled. It opens a window underneath with two tabs.
5. "Model Values" tab:
  a. Specify number of samples in text box
  b. The table lists all the model settings, double click on the Default column to change values. All values will be included in the analysis settings regardless of whether edited or not.
7. "File Uploads" tab:
  a. This panel has different files categories, which are directly imported from the data_settings section of the model settings. Files can be uploaded using the Browse buttons and selected from the tables. Note: only the selected files will be included in the analysis settings. 
8. Click "Apply" to save all of the changes
9. Give a name to the analysis and submit
10. Proceed to "Configure Output & Run"

Some of the model settings are also transferred to the "Configure Output & Run" step in the "Model Parameters" panel: Event Set, Event Occurrence, Number of Samples, Loss Threshold, Hazard Intensity Threshold, Min Rp, event_subset. If one parameter is changed in step 2 and appears in step 3, the modified version will be shown in the latter. These parameters can be further modified here and changes are overwritten in the analysis settings. 
